{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jason-lang",
    "module": "jason_active_perception",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "qk7wlxwr5nhs3lfepbynxxu47y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jason-lang",
          "module": "jason",
          "version": {
            "requires": "2.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jason_active_perception-1.3.jar",
          "url": "jason_active_perception-1.3.jar",
          "size": 16292,
          "sha512": "72c420ec6234c9caf3072909dc82aa8e2cb5005c2f2dbd1304c6cce0d5ab78238b6bc117753219b2a029aaf0f41a78f4739cf19bc150e622c800916ba17c2b99",
          "sha256": "f43489118f3cf72a616044d6014adf9bd2543278d3a00cb7011f046d44bfeca2",
          "sha1": "92254e49e0f3473f53f7599f042a0d44977ade3f",
          "md5": "fa89f13a0c6c809e815699de99da4b8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jason-lang",
          "module": "jason",
          "version": {
            "requires": "2.5-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "jason_active_perception-1.3.jar",
          "url": "jason_active_perception-1.3.jar",
          "size": 16292,
          "sha512": "72c420ec6234c9caf3072909dc82aa8e2cb5005c2f2dbd1304c6cce0d5ab78238b6bc117753219b2a029aaf0f41a78f4739cf19bc150e622c800916ba17c2b99",
          "sha256": "f43489118f3cf72a616044d6014adf9bd2543278d3a00cb7011f046d44bfeca2",
          "sha1": "92254e49e0f3473f53f7599f042a0d44977ade3f",
          "md5": "fa89f13a0c6c809e815699de99da4b8e"
        }
      ]
    }
  ]
}
